# Generated by Django 5.2.9 on 2026-01-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='membership',
            field=models.CharField(choices=[('normal', 'Normal'), ('golden', 'Golden'), ('premium', 'Premium')], default='normal', max_length=20),
        ),
    ]
